global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8000"]

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8000"]

  - job_name: "forecast-engine"
    static_configs:
      - targets: ["forecast-engine:8000"]

  - job_name: "ai-reasoning-agent"
    static_configs:
      - targets: ["ai-reasoning-agent:8000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
